name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Pull latest changes from Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://Bvadaliya3005:$HF_TOKEN@huggingface.co/spaces/Bvadaliya3005/search-engine-LLM || true
          git fetch hf
          git reset --hard hf/main  # Overwrite local changes with remote version
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://Bvadaliya3005:$HF_TOKEN@huggingface.co/spaces/Bvadaliya3005/search-engine-LLM main
